### ISSUE TITLE
Access token cookie is not replaced!

### ISSUE THREAD

**Issue by sb-andy** [bendotcodes/cookies#343]
Hello,

I have a problem:

const cookies = new Cookies();

1) I set initial cookie like this: cookies.set("accessToken", initialAccessToken, { secure: true, });
2) After generating a new access token I use the same: cookies.set("accessToken", newAccessToken, { secure: true, }); 

The problem is: it duplicates. I can see 2 cookies "accessToken". What do I do wrong? Thank you in advance.

**Comment by ryansyrl** [comment]
iam facing the same problem when i refresh the page for some reason the cookies duplicates, and when try to using remove('cookie') the target cookie not removed from the browser. but when i refresh the browser the target cookie that intent to remove, duplicates.

i am using vue 3

**Comment by AllenWilliamson** [comment]
Seems to have to do with the path option when a cookie is set. When you call `setCookie()`, the cookie will be set with the current path. If you try to set the same cookie at a different path, it will create a duplicate. 

I solved this for myself by setting the path option in `setCookie` to be `/`.

e.g.
```js
setCookie('team', teamId, { path: '/' });
```

It would be nice to have an option on the cookie provider to set a default path instead of taking the current path.

**Comment by eXon** [comment]
@AllenWilliamson I agree it would be nice. A default set options will be added in v6.
